from enum import Enum

class BattleType(str, Enum):
    NONE = 'NONE'
    NORMAL = 'NORMAL'
    FIRE = 'FIRE'
    WATER = 'WATER'
    GRASS = 'GRASS'
    ELECTRIC = 'ELECTRIC'
    BUG = 'BUG'
    DRAGON = 'DRAGON'
    FAIRY = 'FAIRY'
    DARK = 'DARK'
    POISON = 'POISON'
    PSYCHIC = 'PSYCHIC'
    GHOST = 'GHOST'
    GROUND = 'GROUND'
    STEEL = 'STEEL'
    ROCK = 'ROCK'
    ICE = 'ICE'
    FIGHTING = 'FIGHTING'
    FLYING = 'FLYING'


class Status(str, Enum):
    NONE = 'NONE'
    ASLEEP = 'ASLEEP'
    CONFUSED = 'CONFUSED'
    POISONED = 'POISONED'
    PARALYZED = 'PARALYZED'
    BURNED = 'BURNED'
    CURSED = 'CURSED'
    FROZEN = 'FROZEN'
    KNOCKED_OUT = 'KNOCKED_OUT'


class Targeting(str, Enum):
    SELF = 'SELF'
    OPPONENT = 'OPPONENT'
    OPPONENT_TARGET = 'OPPONENT_TARGET'
    OPPONENT_ALL = 'OPPONENT_ALL'
    FRIENDLY_TARGET = 'FRIENDLY_TARGET'
    FRIENDLY_ALL = 'FRIENDLY_ALL'


class EffectType(str, Enum):
    ADD_COMBAT_MODIFIER = 'ADD_COMBAT_MODIFIER'
    CLEANSE_COMBAT_MODIFIERS = 'CLEANSE_COMBAT_MODIFIERS'
    ADD_STATUS_EFFECT = 'ADD_STATUS_EFFECT'
    CLEANSE_STATUS_EFFECTS = 'CLEANSE_STATUS_EFFECTS'
    HEAL = 'HEAL'
    DRAIN = 'DRAIN'
    PUSH_OUT = 'PUSH_OUT'
    PULL_IN = 'PULL_IN'
    CHARGE = 'CHARGE'


class CombatModifiers(str, Enum):
    CHARGED_UP = 'CHARGED_UP'
    ACCURACY_DOWN = 'ACCURACY_DOWN'
    ACCURACY_DOWN_DOWN = 'ACCURACY_DOWN_DOWN'
    ACCURACY_UP = 'ACCURACY_UP'
    ACCURACY_UP_UP = 'ACCURACY_UP_UP'
    ATK_UP = 'ATK_UP'
    ATK_UP_UP = 'ATK_UP_UP'
    ATK_DOWN = 'ATK_DOWN'
    ATK_DOWN_DOWN = 'ATK_DOWN_DOWN'
    SPATK_UP = 'SPATK_UP'
    SPATK_UP_UP = 'SPATK_UP_UP'
    SPATK_DOWN = 'SPATK_DOWN'
    SPATK_DOWN_DOWN = 'SPATK_DOWN_DOWN'
    DEF_UP = 'DEF_UP'
    DEF_UP_UP = 'DEF_UP_UP'
    DEF_DOWN = 'DEF_DOWN'
    DEF_DOWN_DOWN = 'DEF_DOWN_DOWN'
    SPDEF_UP = 'SPDEF_UP'
    SPDEF_UP_UP = 'SPDEF_UP_UP'
    SPDEF_DOWN = 'SPDEF_DOWN'
    SPDEF_DOWN_DOWN = 'SPDEF_DOWN_DOWN'
    SPEED_UP = 'SPEED_UP'
    SPEED_UP_UP = 'SPEED_UP_UP'
    SPEED_DOWN = 'SPEED_DOWN'
    SPEED_DOWN_DOWN = 'SPEED_DOWN_DOWN'


class PokemonStat(str, Enum):
    ATTACK = 'ATTACK'
    SPECIAL_ATTACK = 'SPECIAL_ATTACK'
    DEFENSE = 'DEFENSE'
    SPECIAL_DEFENSE = 'SPECIAL_DEFENSE'
    HP = 'HP'
    SPEED = 'SPEED'


class ItemType(str, Enum):
    POTION = 'POTION'
    SUPER_POTION = 'SUPER_POTION'
    POKEBALL = 'POKEBALL'
    GREATBALL = 'GREATBALL'
    POKEFEAST = 'POKEFEAST'